[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
prnt = "9Keg5CgCSSudKKuXJcEMvyksGLbbqgrtaYjoM18uyaGQ"

[programs.mainnet]
prnt = "9Keg5CgCSSudKKuXJcEMvyksGLbbqgrtaYjoM18uyaGQ"

[registry]
url = "https://mainnet.helius-rpc.com/?api-key=f1d5fa66-a4cd-4cb6-a0c3-49c3500e7c0f"

[provider]
cluster = "mainnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
