[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
prnt = "HjxwAMPfrWLYr7XF2hSUHUEXu8KnFSRwHYrFu4T9f9XB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
